-- MySQL Script generated by MySQL Workbench
-- 07/12/15 23:16:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema LoTenemosTodo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LoTenemosTodo` ;

-- -----------------------------------------------------
-- Schema LoTenemosTodo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LoTenemosTodo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
SHOW WARNINGS;
USE `LoTenemosTodo` ;

-- -----------------------------------------------------
-- Table `perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perfil` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `perfil` (
  `id_perfil` VARCHAR(3) NOT NULL,
  `descripcion_perfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_perfil`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuarios` (
  `idusuario` BIGINT NOT NULL,
  `login_usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `apellido_usuario` VARCHAR(45) NOT NULL,
  `correo_usuario` VARCHAR(45) NOT NULL,
  `edad_usuario` INT NOT NULL,
  `id_perfil` VARCHAR(3) NOT NULL,
  `fechaNacimiento_usuario` DATETIME NOT NULL,
  `perfil_id_perfil` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`idusuario`, `perfil_id_perfil`),
  CONSTRAINT `fk_usuarios_perfil1`
    FOREIGN KEY (`perfil_id_perfil`)
    REFERENCES `perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_usuarios_perfil1_idx` ON `usuarios` (`perfil_id_perfil` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `orden_compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `orden_compras` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `orden_compras` (
  `id_oc` BIGINT NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  `total_oc` INT NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `id_usuario` BIGINT NOT NULL,
  `usuarios_idusuario` BIGINT NOT NULL,
  PRIMARY KEY (`id_oc`, `usuarios_idusuario`),
  CONSTRAINT `fk_orden_compras_usuarios`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_orden_compras_usuarios_idx` ON `orden_compras` (`usuarios_idusuario` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipo_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_producto` (
  `idtipo_producto` VARCHAR(5) NOT NULL,
  `descripcion_tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_producto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `productos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `productos` (
  `id_producto` BIGINT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `unidad` INT NOT NULL,
  `id_tipo` VARCHAR(5) NOT NULL,
  `tipo_producto_idtipo_producto` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id_producto`, `tipo_producto_idtipo_producto`),
  CONSTRAINT `fk_productos_tipo_producto1`
    FOREIGN KEY (`tipo_producto_idtipo_producto`)
    REFERENCES `tipo_producto` (`idtipo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_productos_tipo_producto1_idx` ON `productos` (`tipo_producto_idtipo_producto` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `detalle_oc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `detalle_oc` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `detalle_oc` (
  `id_oc` BIGINT NOT NULL,
  `id_producto` BIGINT NOT NULL,
  `cantidad` INT NOT NULL,
  `subtotal` INT NOT NULL,
  `orden_compras_id_oc` BIGINT NOT NULL,
  `orden_compras_usuarios_idusuario` BIGINT NOT NULL,
  `productos_id_producto` BIGINT NOT NULL,
  PRIMARY KEY (`id_oc`, `orden_compras_id_oc`, `orden_compras_usuarios_idusuario`, `productos_id_producto`),
  CONSTRAINT `fk_detalle_oc_orden_compras1`
    FOREIGN KEY (`orden_compras_id_oc` , `orden_compras_usuarios_idusuario`)
    REFERENCES `orden_compras` (`id_oc` , `usuarios_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_oc_productos1`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_detalle_oc_orden_compras1_idx` ON `detalle_oc` (`orden_compras_id_oc` ASC, `orden_compras_usuarios_idusuario` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_detalle_oc_productos1_idx` ON `detalle_oc` (`productos_id_producto` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
